import{BadRequestException,Body,Controller,Get,HttpCode,Inject,Param,Post,Query,Req}from"@nestjs/common";import type{Request}from"express";import{Public}from"../identity/public-route.js";import{RequestActorService}from"../identity/request-actor.service.js";import type{EventTopic}from"./integration.repository.js";import{IntegrationsService}from"./integrations.service.js";
@Controller("v1/integrations")export class IntegrationsController{constructor(@Inject(RequestActorService)private actors:RequestActorService,@Inject(IntegrationsService)private integrations:IntegrationsService){}
@Post("webhooks")async create(@Req()q:Request,@Body()b:unknown){return{data:await this.integrations.createSubscription(await this.actors.fromRequest(q),str(b,"endpoint"),strings(b,"topics"))};}
@Get("webhooks")async subscriptions(@Req()q:Request){return{data:await this.integrations.listSubscriptions(await this.actors.fromRequest(q))};}
@Get("webhook-attempts")async attempts(@Req()q:Request){return{data:await this.integrations.listAttempts(await this.actors.fromRequest(q))};}
@Post("webhook-attempts/:id/dispatch")@HttpCode(200)async dispatch(@Req()q:Request,@Param("id")id:string){return{data:await this.integrations.dispatch(await this.actors.fromRequest(q),id)};}
@Post("webhook-attempts/:id/replay")@HttpCode(200)async replay(@Req()q:Request,@Param("id")id:string){return{data:await this.integrations.replay(await this.actors.fromRequest(q),id)};}
@Public()@Get("events/public")async publicFeed(@Query("after")after:string|undefined,@Query("limit")limit:string|undefined){return{public:true,data:await this.integrations.publicFeed(after,limit===undefined?50:Number(limit))};}
@Get("events/private")async privateFeed(@Req()q:Request,@Query("after")after:string|undefined,@Query("limit")limit:string|undefined){return{public:false,data:await this.integrations.privateFeed(await this.actors.fromRequest(q),after,limit===undefined?50:Number(limit))};}
@Post("events")async publish(@Req()q:Request,@Body()b:unknown){const actor=await this.actors.fromRequest(q);if(!actor.personas.includes("ExchangeAdmin"))throw new BadRequestException("ExchangeAdmin required");const topic=str(b,"topic")as EventTopic;return{data:await this.integrations.publish(topic,optional(b,"organizationId"),str(b,"subjectId"),object(b,"payload"))};}}
function prop(b:unknown,n:string){if(typeof b!=="object"||b===null||!(n in b))throw new BadRequestException(`${n} is required`);return(b as Record<string,unknown>)[n];}function str(b:unknown,n:string){const v=prop(b,n);if(typeof v!=="string"||v.trim()==="")throw new BadRequestException(`${n} must be a string`);return v.trim();}function optional(b:unknown,n:string){if(typeof b!=="object"||b===null||!(n in b))return undefined;return str(b,n);}function strings(b:unknown,n:string){const v=prop(b,n);if(!Array.isArray(v)||!v.every(x=>typeof x==="string"&&x.trim()!==""))throw new BadRequestException(`${n} must be a string array`);return v as string[];}function object(b:unknown,n:string){const v=prop(b,n);if(typeof v!=="object"||v===null||Array.isArray(v))throw new BadRequestException(`${n} must be an object`);return v as Record<string,unknown>;}