import{authorize}from"@bordchamp/authz";import type{ActorContext,EntityStatus}from"@bordchamp/domain";
import{BadRequestException,ConflictException,ForbiddenException,Inject,Injectable,NotFoundException}from"@nestjs/common";
import{INVENTORY_REPOSITORY,InventoryConflictError,type InventoryLot,type InventoryRepository}from"../inventory/inventory.repository.js";
import{ORGANIZATION_REPOSITORY,type OrganizationRepository}from"../organizations/organization.repository.js";
import{COMPLIANCE_REPOSITORY,ComplianceConflictError,type ComplianceDocument,type ComplianceRepository,type LineageEdge,type Recall}from"./compliance.repository.js";
@Injectable()export class ComplianceService{
 constructor(@Inject(COMPLIANCE_REPOSITORY)private compliance:ComplianceRepository,@Inject(INVENTORY_REPOSITORY)private inventory:InventoryRepository,@Inject(ORGANIZATION_REPOSITORY)private organizations:OrganizationRepository){}
 async submitDocument(actor:ActorContext,organizationId:string,type:string,documentReference:string,evidenceReference:string,issuedAt:string,validUntil:string){const org=await this.organizations.get(organizationId);if(!org)throw new NotFoundException("Organization not found");this.assert("compliance.document.submit",actor,org.status,organizationId);validateDate(issuedAt,"issuedAt");validateDate(validUntil,"validUntil");if(new Date(validUntil)<=new Date(issuedAt))throw new BadRequestException("validUntil must be after issuedAt");const id=key(documentReference);const now=new Date().toISOString();return this.compliance.submitDocument({id,organizationId,type,documentReference,evidenceReference,issuedAt,validUntil,status:"submitted",submittedAt:now},actor.userId);}
 async listDocuments(actor:ActorContext,organizationId:string){const org=await this.organizations.get(organizationId);if(!org)throw new NotFoundException("Organization not found");this.assert("compliance.document.view",actor,org.status,organizationId);return(await this.compliance.listDocuments(organizationId)).map(d=>({...d,effectiveStatus:effective(d)}));}
 async reviewDocument(actor:ActorContext,organizationId:string,id:string,status:"approved"|"rejected",reason:string,etag:string){const doc=await this.compliance.getDocument(organizationId,id);if(!doc)throw new NotFoundException("Compliance document not found");if(doc.status!=="submitted")throw new BadRequestException("Document was already reviewed");this.assert("compliance.document.review",actor,"active",organizationId);return this.map(()=>this.compliance.reviewDocument(organizationId,id,status,reason,etag,actor.userId));}
 async registerLineage(actor:ActorContext,parentLotIds:readonly string[],childLotId:string,transformationType:string){const ids=[...new Set(parentLotIds)];if(ids.length===0)throw new BadRequestException("At least one parent lot is required");if(ids.includes(childLotId))throw new BadRequestException("A lot cannot derive from itself");const child=await this.requireLot(childLotId);this.assert("traceability.lineage.register",actor,lotState(child),child.ownerOrganizationId);const parents=await Promise.all(ids.map(id=>this.requireLot(id)));for(const parent of parents){if(parent.ownerOrganizationId!==child.ownerOrganizationId)throw new BadRequestException("Lineage lots must share an owner organization");if(parent.category!==child.category||parent.commodityCode!==child.commodityCode)throw new BadRequestException("Lineage lots must share category and commodity");if(parent.quantity.unitCode!==child.quantity.unitCode||parent.quantity.scale!==child.quantity.scale)throw new BadRequestException("Lineage quantities must share unit and scale");const descendants=await this.walk(parent.id,"children");if(descendants.has(child.id))throw new BadRequestException("Lineage edge already exists");const childDescendants=await this.walk(child.id,"children");if(childDescendants.has(parent.id))throw new BadRequestException("Lineage cycle is not allowed");}
 const total=parents.reduce((sum,p)=>sum+p.quantity.value,0);if(!Number.isSafeInteger(total)||child.quantity.value>total)throw new BadRequestException("Child quantity exceeds parent quantity");const now=new Date().toISOString();for(const parent of parents)await this.compliance.registerLineage({parentLotId:parent.id,childLotId:child.id,transformationType,createdAt:now,actorUserId:actor.userId});return{parentLotIds:ids,childLotId,transformationType};}
 async trace(actor:ActorContext,lotId:string){const root=await this.requireLot(lotId);this.assert("traceability.view",actor,lotState(root),root.ownerOrganizationId);const ancestors=await this.walk(lotId,"parents");const descendants=await this.walk(lotId,"children");const ids=[...new Set([lotId,...ancestors,...descendants])];const lots=await Promise.all(ids.map(id=>this.requireLot(id)));const edges:LineageEdge[]=[];for(const id of ids)edges.push(...await this.compliance.listChildren(id));return{rootLotId:lotId,lots,edges,ancestorLotIds:[...ancestors],descendantLotIds:[...descendants]};}
 async applyRecall(actor:ActorContext,reference:string,rootLotId:string,reason:string){const root=await this.requireLot(rootLotId);this.assert("compliance.hold.manage",actor,lotState(root),root.ownerOrganizationId);const id=`RECALL-${key(reference)}`;let recall=await this.compliance.getRecall(id);if(recall?.status==="applied")return this.recallView(recall);if(recall?.status==="released")throw new ConflictException("Released recall reference cannot be reused");if(!recall){const now=new Date().toISOString();recall=await this.compliance.createRecall({id,reference,rootLotId,reason,status:"applying",createdAt:now,updatedAt:now},actor.userId);}const descendants=await this.walk(rootLotId,"children");for(const lotId of [rootLotId,...descendants]){const lot=await this.requireLot(lotId);let outcome:"held"|"alreadyHeld"|"inactive"="held";if(lot.status==="inactive")outcome="inactive";else if(lot.status==="quarantined")outcome="alreadyHeld";else await this.mapInventory(()=>this.inventory.quarantine(lot.id,recallReason(recall!),lot.etag,actor.userId));await this.compliance.recordImpact(id,{lotId,outcome,recordedAt:new Date().toISOString()});}const updated=await this.map(()=>this.compliance.updateRecall(id,"applied",recall!.etag,actor.userId));return this.recallView(updated);}
 async releaseRecall(actor:ActorContext,id:string,etag:string){const recall=await this.requireRecall(id);this.assert("compliance.hold.manage",actor,"suspended",recall.rootLotId);if(recall.status!=="applied")throw new BadRequestException("Only an applied recall can be released");const impacts=await this.compliance.listImpacts(id);for(const impact of impacts){const lot=await this.requireLot(impact.lotId);if(lot.status==="quarantined"&&lot.quarantineReason===recallReason(recall)){await this.mapInventory(()=>this.inventory.releaseQuarantine(lot.id,`Recall ${id} released`,lot.etag,actor.userId));await this.compliance.recordImpact(id,{lotId:lot.id,outcome:"released",recordedAt:new Date().toISOString()});}}const updated=await this.map(()=>this.compliance.updateRecall(id,"released",etag,actor.userId));return this.recallView(updated);}
 async getRecall(actor:ActorContext,id:string){const recall=await this.requireRecall(id);this.assert("traceability.view",actor,recall.status==="released"?"inactive":"suspended",(await this.requireLot(recall.rootLotId)).ownerOrganizationId);return this.recallView(recall);}
 async createMovementRestriction(actor:ActorContext,reference:string,regionCode:string,commodityCode:string|undefined,reason:string,effectiveFrom:string,effectiveUntil:string|undefined){this.assert("compliance.hold.manage",actor,"active",regionCode);validateDate(effectiveFrom,"effectiveFrom");if(effectiveUntil!==undefined){validateDate(effectiveUntil,"effectiveUntil");if(new Date(effectiveUntil)<=new Date(effectiveFrom))throw new BadRequestException("effectiveUntil must be after effectiveFrom");}const id=key(reference);const now=new Date().toISOString();return this.compliance.createMovementRestriction({id,reference,regionCode:regionCode.toUpperCase(),...(commodityCode===undefined?{}:{commodityCode:commodityCode.toUpperCase()}),reason,effectiveFrom,...(effectiveUntil===undefined?{}:{effectiveUntil}),status:"active",createdAt:now,updatedAt:now},actor.userId);}
 async listMovementRestrictions(actor:ActorContext,regionCode:string){this.assert("compliance.hold.manage",actor,"active",regionCode);return this.compliance.listMovementRestrictions(regionCode.toUpperCase());}
 async releaseMovementRestriction(actor:ActorContext,regionCode:string,id:string,etag:string){this.assert("compliance.hold.manage",actor,"suspended",regionCode);return this.map(()=>this.compliance.releaseMovementRestriction(regionCode.toUpperCase(),id,etag,actor.userId));}
 private async recallView(recall:Recall){return{recall,impacts:await this.compliance.listImpacts(recall.id)};}private async requireRecall(id:string){const r=await this.compliance.getRecall(id);if(!r)throw new NotFoundException("Recall not found");return r;}private async requireLot(id:string){const l=await this.inventory.get(id);if(!l)throw new NotFoundException("Inventory lot not found");return l;}
 private async walk(start:string,direction:"parents"|"children"){const found=new Set<string>();let frontier=[start];for(let depth=0;frontier.length>0&&depth<20;depth++){const next:string[]=[];for(const id of frontier){const edges=direction==="children"?await this.compliance.listChildren(id):await this.compliance.listParents(id);for(const edge of edges){const candidate=direction==="children"?edge.childLotId:edge.parentLotId;if(!found.has(candidate)){found.add(candidate);next.push(candidate);if(found.size>1000)throw new BadRequestException("Traceability graph exceeds the supported limit");}}}frontier=next;}return found;}
 private assert(action:"compliance.document.submit"|"compliance.document.view"|"compliance.document.review"|"traceability.lineage.register"|"traceability.view"|"compliance.hold.manage",actor:ActorContext,state:EntityStatus,org:string){const result=authorize({action,actor,entityStatus:state,resourceOrganizationId:org});if(!result.allowed)throw new ForbiddenException(result.reason);}private async map<T>(op:()=>Promise<T>){try{return await op();}catch(e){if(e instanceof ComplianceConflictError)throw new ConflictException("Compliance state changed; refresh and retry");throw e;}}private async mapInventory<T>(op:()=>Promise<T>){try{return await op();}catch(e){if(e instanceof InventoryConflictError)throw new ConflictException("Lot state changed during recall; retry the recall");throw e;}}}
function effective(d:ComplianceDocument){return d.status==="approved"&&new Date(d.validUntil).getTime()<=Date.now()?"expired":d.status;}function validateDate(value:string,name:string){if(!Number.isFinite(new Date(value).getTime()))throw new BadRequestException(`${name} must be an ISO date`);}function key(value:string){return Buffer.from(value).toString("base64url");}function lotState(l:InventoryLot):EntityStatus{return l.status==="quarantined"?"suspended":["inactive","sold"].includes(l.status)?"inactive":"active";}function recallReason(r:Recall){return`Recall ${r.id}: ${r.reason}`;}