import{BadRequestException,Body,Controller,Get,Headers,HttpCode,Inject,Param,Post,Req,Res}from"@nestjs/common";import type{Request,Response}from"express";import{RequestActorService}from"../identity/request-actor.service.js";import{ComplianceService}from"./compliance.service.js";
@Controller("v1")export class ComplianceController{constructor(@Inject(RequestActorService)private actors:RequestActorService,@Inject(ComplianceService)private compliance:ComplianceService){}
@Post("compliance/documents")async submit(@Req()q:Request,@Body()b:unknown,@Res({passthrough:true})r:Response){const d=await this.compliance.submitDocument(await this.actors.fromRequest(q),str(b,"organizationId"),str(b,"type"),str(b,"documentReference"),str(b,"evidenceReference"),str(b,"issuedAt"),str(b,"validUntil"));r.setHeader("ETag",d.etag);return{data:d};}
@Get("compliance/organizations/:organizationId/documents")async documents(@Req()q:Request,@Param("organizationId")o:string){return{data:await this.compliance.listDocuments(await this.actors.fromRequest(q),o)};}
@Post("compliance/organizations/:organizationId/documents/:id/review")@HttpCode(200)async review(@Req()q:Request,@Param("organizationId")o:string,@Param("id")id:string,@Headers("if-match")e:string|undefined,@Body()b:unknown,@Res({passthrough:true})r:Response){const status=str(b,"status");if(!["approved","rejected"].includes(status))throw new BadRequestException("Invalid review status");const d=await this.compliance.reviewDocument(await this.actors.fromRequest(q),o,id,status as"approved"|"rejected",str(b,"reason"),tag(e));r.setHeader("ETag",d.etag);return{data:d};}
@Post("traceability/lineage")async lineage(@Req()q:Request,@Body()b:unknown){return{data:await this.compliance.registerLineage(await this.actors.fromRequest(q),strings(b,"parentLotIds"),str(b,"childLotId"),str(b,"transformationType"))};}
@Get("traceability/lots/:id")async trace(@Req()q:Request,@Param("id")id:string){return{data:await this.compliance.trace(await this.actors.fromRequest(q),id)};}
@Post("compliance/recalls")async recall(@Req()q:Request,@Body()b:unknown,@Res({passthrough:true})r:Response){const d=await this.compliance.applyRecall(await this.actors.fromRequest(q),str(b,"reference"),str(b,"rootLotId"),str(b,"reason"));r.setHeader("ETag",d.recall.etag);return{data:d};}
@Get("compliance/recalls/:id")async getRecall(@Req()q:Request,@Param("id")id:string,@Res({passthrough:true})r:Response){const d=await this.compliance.getRecall(await this.actors.fromRequest(q),id);r.setHeader("ETag",d.recall.etag);return{data:d};}
@Post("compliance/recalls/:id/release")@HttpCode(200)async release(@Req()q:Request,@Param("id")id:string,@Headers("if-match")e:string|undefined,@Res({passthrough:true})r:Response){const d=await this.compliance.releaseRecall(await this.actors.fromRequest(q),id,tag(e));r.setHeader("ETag",d.recall.etag);return{data:d};}
@Post("compliance/movement-restrictions")async createRestriction(@Req()q:Request,@Body()b:unknown,@Res({passthrough:true})r:Response){const d=await this.compliance.createMovementRestriction(await this.actors.fromRequest(q),str(b,"reference"),str(b,"regionCode"),optional(b,"commodityCode"),str(b,"reason"),str(b,"effectiveFrom"),optional(b,"effectiveUntil"));r.setHeader("ETag",d.etag);return{data:d};}
@Get("compliance/movement-restrictions/:regionCode")async restrictions(@Req()q:Request,@Param("regionCode")region:string){return{data:await this.compliance.listMovementRestrictions(await this.actors.fromRequest(q),region)};}
@Post("compliance/movement-restrictions/:regionCode/:id/release")@HttpCode(200)async releaseRestriction(@Req()q:Request,@Param("regionCode")region:string,@Param("id")id:string,@Headers("if-match")e:string|undefined,@Res({passthrough:true})r:Response){const d=await this.compliance.releaseMovementRestriction(await this.actors.fromRequest(q),region,id,tag(e));r.setHeader("ETag",d.etag);return{data:d};}}
function prop(b:unknown,n:string){if(typeof b!=="object"||b===null||!(n in b))throw new BadRequestException(`${n} is required`);return(b as Record<string,unknown>)[n];}function str(b:unknown,n:string){const v=prop(b,n);if(typeof v!=="string"||v.trim()==="")throw new BadRequestException(`${n} must be a string`);return v.trim();}function optional(b:unknown,n:string){if(typeof b!=="object"||b===null||!(n in b))return undefined;return str(b,n);}function strings(b:unknown,n:string){const v=prop(b,n);if(!Array.isArray(v)||!v.every(x=>typeof x==="string"&&x.trim()!==""))throw new BadRequestException(`${n} must be a string array`);return v as string[];}function tag(v:string|undefined){if(!v)throw new BadRequestException("If-Match header is required");return v;}