import { TableClient, TableTransaction, type TableEntity } from "@azure/data-tables";
import { randomUUID } from "node:crypto";
import { createTableClient, hasTableStorageConfiguration } from "../storage/table-client.js";

export const COMPLIANCE_REPOSITORY = Symbol("COMPLIANCE_REPOSITORY");
export interface ComplianceDocument {
  readonly id: string; readonly organizationId: string; readonly type: string;
  readonly documentReference: string; readonly evidenceReference: string;
  readonly issuedAt: string; readonly validUntil: string;
  readonly status: "submitted" | "approved" | "rejected";
  readonly reviewReason?: string; readonly submittedAt: string; readonly reviewedAt?: string;
  readonly reviewedByUserId?: string; readonly etag: string;
}
export interface LineageEdge { readonly parentLotId: string; readonly childLotId: string;
  readonly transformationType: string; readonly createdAt: string; readonly actorUserId: string; }
export interface Recall { readonly id: string; readonly reference: string; readonly rootLotId: string;
  readonly reason: string; readonly status: "applying" | "applied" | "released";
  readonly createdAt: string; readonly updatedAt: string; readonly etag: string; }
export interface RecallImpact { readonly lotId: string; readonly outcome: "held" | "alreadyHeld" | "inactive" | "released"; readonly recordedAt: string; }
export interface MovementRestriction { readonly id:string;readonly reference:string;readonly regionCode:string;
  readonly commodityCode?:string;readonly reason:string;readonly effectiveFrom:string;readonly effectiveUntil?:string;
  readonly status:"active"|"released";readonly createdAt:string;readonly updatedAt:string;readonly etag:string; }
export class ComplianceConflictError extends Error {}
export interface ComplianceRepository {
  submitDocument(value: Omit<ComplianceDocument,"etag">, actorUserId:string):Promise<ComplianceDocument>;
  getDocument(organizationId:string,id:string):Promise<ComplianceDocument|undefined>;
  listDocuments(organizationId:string):Promise<readonly ComplianceDocument[]>;
  reviewDocument(organizationId:string,id:string,status:"approved"|"rejected",reason:string,etag:string,actorUserId:string):Promise<ComplianceDocument>;
  registerLineage(edge:LineageEdge):Promise<void>; listChildren(lotId:string):Promise<readonly LineageEdge[]>; listParents(lotId:string):Promise<readonly LineageEdge[]>;
  createRecall(value:Omit<Recall,"etag">,actorUserId:string):Promise<Recall>;getRecall(id:string):Promise<Recall|undefined>;
  recordImpact(recallId:string,impact:RecallImpact):Promise<void>;listImpacts(recallId:string):Promise<readonly RecallImpact[]>;
  updateRecall(id:string,status:"applied"|"released",etag:string,actorUserId:string):Promise<Recall>;
  createMovementRestriction(value:Omit<MovementRestriction,"etag">,actorUserId:string):Promise<MovementRestriction>;
  listMovementRestrictions(regionCode:string):Promise<readonly MovementRestriction[]>;
  releaseMovementRestriction(regionCode:string,id:string,etag:string,actorUserId:string):Promise<MovementRestriction>;
}
interface DocumentEntity extends TableEntity { id:string;organizationId:string;type:string;documentReference:string;evidenceReference:string;issuedAt:string;validUntil:string;status:"submitted"|"approved"|"rejected";reviewReason?:string;submittedAt:string;reviewedAt?:string;reviewedByUserId?:string; }
function docEntity(d:Omit<ComplianceDocument,"etag">):DocumentEntity{return{partitionKey:`ORG:${d.organizationId}`,rowKey:`DOC:${d.id}`,id:d.id,organizationId:d.organizationId,type:d.type,documentReference:d.documentReference,evidenceReference:d.evidenceReference,issuedAt:d.issuedAt,validUntil:d.validUntil,status:d.status,...(d.reviewReason===undefined?{}:{reviewReason:d.reviewReason}),submittedAt:d.submittedAt,...(d.reviewedAt===undefined?{}:{reviewedAt:d.reviewedAt}),...(d.reviewedByUserId===undefined?{}:{reviewedByUserId:d.reviewedByUserId})};}
function toDoc(e:DocumentEntity&{etag?:string}):ComplianceDocument{return{id:e.id,organizationId:e.organizationId,type:e.type,documentReference:e.documentReference,evidenceReference:e.evidenceReference,issuedAt:e.issuedAt,validUntil:e.validUntil,status:e.status,...(e.reviewReason===undefined?{}:{reviewReason:e.reviewReason}),submittedAt:e.submittedAt,...(e.reviewedAt===undefined?{}:{reviewedAt:e.reviewedAt}),...(e.reviewedByUserId===undefined?{}:{reviewedByUserId:e.reviewedByUserId}),etag:e.etag??""};}
interface RecallEntity extends TableEntity { id:string;reference:string;rootLotId:string;reason:string;status:"applying"|"applied"|"released";createdAt:string;updatedAt:string; }
function recallEntity(r:Omit<Recall,"etag">):RecallEntity{return{partitionKey:r.id,rowKey:"PROFILE",id:r.id,reference:r.reference,rootLotId:r.rootLotId,reason:r.reason,status:r.status,createdAt:r.createdAt,updatedAt:r.updatedAt};}
function toRecall(e:RecallEntity&{etag?:string}):Recall{return{id:e.id,reference:e.reference,rootLotId:e.rootLotId,reason:e.reason,status:e.status,createdAt:e.createdAt,updatedAt:e.updatedAt,etag:e.etag??""};}
function audit(partition:string,type:string,actor:string,at:string,details:string):TableEntity{return{partitionKey:partition,rowKey:`EVENT:${at}:${randomUUID()}`,eventType:type,actorUserId:actor,occurredAt:at,details};}
function impactEntity(recallId:string,i:RecallImpact):TableEntity{return{partitionKey:recallId,rowKey:`IMPACT:${i.lotId}`,...i};}
function toImpact(e:TableEntity&Record<string,unknown>):RecallImpact{return{lotId:e.lotId as string,outcome:e.outcome as RecallImpact["outcome"],recordedAt:e.recordedAt as string};}
export class InMemoryComplianceRepository implements ComplianceRepository {
  private docs=new Map<string,ComplianceDocument>();private children=new Map<string,LineageEdge[]>();private parents=new Map<string,LineageEdge[]>();private recalls=new Map<string,Recall>();private impacts=new Map<string,Map<string,RecallImpact>>();private restrictions=new Map<string,MovementRestriction>();private version=0;
  async submitDocument(v:Omit<ComplianceDocument,"etag">){const k=`${v.organizationId}:${v.id}`;const x=this.docs.get(k);if(x)return x;const d={...v,etag:this.next()};this.docs.set(k,d);return d;}
  async getDocument(o:string,id:string){return this.docs.get(`${o}:${id}`);}async listDocuments(o:string){return[...this.docs.values()].filter(d=>d.organizationId===o);}
  async reviewDocument(o:string,id:string,status:"approved"|"rejected",reason:string,etag:string,actor:string){const k=`${o}:${id}`;const c=this.docs.get(k);if(!c||c.etag!==etag)throw new ComplianceConflictError(id);const d={...c,status,reviewReason:reason,reviewedAt:new Date().toISOString(),reviewedByUserId:actor,etag:this.next()};this.docs.set(k,d);return d;}
  async registerLineage(e:LineageEdge){if(!(this.children.get(e.parentLotId)??[]).some(x=>x.childLotId===e.childLotId)){this.children.set(e.parentLotId,[...(this.children.get(e.parentLotId)??[]),e]);this.parents.set(e.childLotId,[...(this.parents.get(e.childLotId)??[]),e]);}}
  async listChildren(id:string){return this.children.get(id)??[];}async listParents(id:string){return this.parents.get(id)??[];}
  async createRecall(v:Omit<Recall,"etag">){const x=this.recalls.get(v.id);if(x)return x;const r={...v,etag:this.next()};this.recalls.set(v.id,r);return r;}async getRecall(id:string){return this.recalls.get(id);}
  async recordImpact(id:string,i:RecallImpact){const m=this.impacts.get(id)??new Map<string,RecallImpact>();m.set(i.lotId,i);this.impacts.set(id,m);}async listImpacts(id:string){return[...(this.impacts.get(id)?.values()??[])];}
  async updateRecall(id:string,status:"applied"|"released",etag:string){const c=this.recalls.get(id);if(!c||c.etag!==etag)throw new ComplianceConflictError(id);const r={...c,status,updatedAt:new Date().toISOString(),etag:this.next()};this.recalls.set(id,r);return r;}
  async createMovementRestriction(v:Omit<MovementRestriction,"etag">){const k=`${v.regionCode}:${v.id}`;const x=this.restrictions.get(k);if(x)return x;const r={...v,etag:this.next()};this.restrictions.set(k,r);return r;}async listMovementRestrictions(region:string){return[...this.restrictions.values()].filter(r=>r.regionCode===region);}async releaseMovementRestriction(region:string,id:string,etag:string){const k=`${region}:${id}`;const c=this.restrictions.get(k);if(!c||c.etag!==etag)throw new ComplianceConflictError(id);const r={...c,status:"released" as const,updatedAt:new Date().toISOString(),etag:this.next()};this.restrictions.set(k,r);return r;}private next(){this.version+=1;return`W/\"${this.version}\"`;}}
export class AzureTableComplianceRepository implements ComplianceRepository {
  constructor(private compliance:TableClient,private lineage:TableClient){}
  async submitDocument(v:Omit<ComplianceDocument,"etag">,actor:string){const x=await this.getDocument(v.organizationId,v.id);if(x)return x;const tx=new TableTransaction();tx.createEntity(docEntity(v));tx.createEntity(audit(`ORG:${v.organizationId}`,"compliance.documentSubmitted",actor,v.submittedAt,v.id));await this.submit(this.compliance,tx);return this.requireDoc(v.organizationId,v.id);}
  async getDocument(o:string,id:string){try{return toDoc(await this.compliance.getEntity<DocumentEntity>(`ORG:${o}`,`DOC:${id}`));}catch(e){if(code(e,404))return undefined;throw e;}}
  async listDocuments(o:string){const out:ComplianceDocument[]=[];for await(const e of this.compliance.listEntities<DocumentEntity>({queryOptions:{filter:`PartitionKey eq 'ORG:${o}' and RowKey ge 'DOC:' and RowKey lt 'DOD:'`}}))out.push(toDoc(e));return out;}
  async reviewDocument(o:string,id:string,status:"approved"|"rejected",reason:string,etag:string,actor:string){const c=await this.requireDoc(o,id);const now=new Date().toISOString();const n={...c,status,reviewReason:reason,reviewedAt:now,reviewedByUserId:actor};const tx=new TableTransaction();tx.updateEntity(docEntity(n),"Replace",{etag});tx.createEntity(audit(`ORG:${o}`,"compliance.documentReviewed",actor,now,`${id}:${status}`));await this.submit(this.compliance,tx);return this.requireDoc(o,id);}
  async registerLineage(e:LineageEdge){await this.lineage.upsertEntity({partitionKey:`PARENT:${e.parentLotId}`,rowKey:`CHILD:${e.childLotId}`,...e},"Replace");await this.lineage.upsertEntity({partitionKey:`CHILD:${e.childLotId}`,rowKey:`PARENT:${e.parentLotId}`,...e},"Replace");}
  async listChildren(id:string){const out:LineageEdge[]=[];for await(const e of this.lineage.listEntities({queryOptions:{filter:`PartitionKey eq 'PARENT:${id}'`}}))out.push(edge(e));return out;}
  async listParents(id:string){const out:LineageEdge[]=[];for await(const e of this.lineage.listEntities({queryOptions:{filter:`PartitionKey eq 'CHILD:${id}'`}}))out.push(edge(e));return out;}
  async createRecall(v:Omit<Recall,"etag">,actor:string){const x=await this.getRecall(v.id);if(x)return x;const tx=new TableTransaction();tx.createEntity(recallEntity(v));tx.createEntity(audit(v.id,"recall.created",actor,v.createdAt,v.rootLotId));await this.submit(this.compliance,tx);return this.requireRecall(v.id);}
  async getRecall(id:string){try{return toRecall(await this.compliance.getEntity<RecallEntity>(id,"PROFILE"));}catch(e){if(code(e,404))return undefined;throw e;}}
  async recordImpact(id:string,i:RecallImpact){await this.compliance.upsertEntity(impactEntity(id,i),"Replace");}async listImpacts(id:string){const out:RecallImpact[]=[];for await(const e of this.compliance.listEntities({queryOptions:{filter:`PartitionKey eq '${id}' and RowKey ge 'IMPACT:' and RowKey lt 'IMPACU:'`}}))out.push(toImpact(e as TableEntity&Record<string,unknown>));return out;}
  async updateRecall(id:string,status:"applied"|"released",etag:string,actor:string){const c=await this.requireRecall(id);const now=new Date().toISOString();const tx=new TableTransaction();tx.updateEntity(recallEntity({...c,status,updatedAt:now}),"Replace",{etag});tx.createEntity(audit(id,`recall.${status}`,actor,now,status));await this.submit(this.compliance,tx);return this.requireRecall(id);}
  async createMovementRestriction(v:Omit<MovementRestriction,"etag">,actor:string){const existing=(await this.listMovementRestrictions(v.regionCode)).find(r=>r.id===v.id);if(existing)return existing;const tx=new TableTransaction();tx.createEntity(restrictionEntity(v));tx.createEntity(audit(`REGION:${v.regionCode}`,"movementRestriction.created",actor,v.createdAt,v.id));await this.submit(this.compliance,tx);return this.requireRestriction(v.regionCode,v.id);}
  async listMovementRestrictions(region:string){const out:MovementRestriction[]=[];for await(const e of this.compliance.listEntities<RestrictionEntity>({queryOptions:{filter:`PartitionKey eq 'REGION:${region}' and RowKey ge 'RESTRICTION:' and RowKey lt 'RESTRICTIOO:'`}}))out.push(toRestriction(e));return out;}
  async releaseMovementRestriction(region:string,id:string,etag:string,actor:string){const c=await this.requireRestriction(region,id);const now=new Date().toISOString();const tx=new TableTransaction();tx.updateEntity(restrictionEntity({...c,status:"released",updatedAt:now}),"Replace",{etag});tx.createEntity(audit(`REGION:${region}`,"movementRestriction.released",actor,now,id));await this.submit(this.compliance,tx);return this.requireRestriction(region,id);}
  private async requireDoc(o:string,id:string){const d=await this.getDocument(o,id);if(!d)throw new Error("Document not found");return d;}private async requireRecall(id:string){const r=await this.getRecall(id);if(!r)throw new Error("Recall not found");return r;}private async requireRestriction(region:string,id:string){try{return toRestriction(await this.compliance.getEntity<RestrictionEntity>(`REGION:${region}`,`RESTRICTION:${id}`));}catch(e){if(code(e,404))throw new Error("Restriction not found");throw e;}}private async submit(c:TableClient,tx:TableTransaction){try{await c.submitTransaction(tx.actions);}catch(e){if(code(e,409)||code(e,412))throw new ComplianceConflictError("Compliance conflict");throw e;}}}
interface RestrictionEntity extends TableEntity{id:string;reference:string;regionCode:string;commodityCode?:string;reason:string;effectiveFrom:string;effectiveUntil?:string;status:"active"|"released";createdAt:string;updatedAt:string;}
function restrictionEntity(r:Omit<MovementRestriction,"etag">):RestrictionEntity{return{partitionKey:`REGION:${r.regionCode}`,rowKey:`RESTRICTION:${r.id}`,id:r.id,reference:r.reference,regionCode:r.regionCode,...(r.commodityCode===undefined?{}:{commodityCode:r.commodityCode}),reason:r.reason,effectiveFrom:r.effectiveFrom,...(r.effectiveUntil===undefined?{}:{effectiveUntil:r.effectiveUntil}),status:r.status,createdAt:r.createdAt,updatedAt:r.updatedAt};}
function toRestriction(e:RestrictionEntity&{etag?:string}):MovementRestriction{return{id:e.id,reference:e.reference,regionCode:e.regionCode,...(e.commodityCode===undefined?{}:{commodityCode:e.commodityCode}),reason:e.reason,effectiveFrom:e.effectiveFrom,...(e.effectiveUntil===undefined?{}:{effectiveUntil:e.effectiveUntil}),status:e.status,createdAt:e.createdAt,updatedAt:e.updatedAt,etag:e.etag??""};}
function edge(e:Record<string,unknown>):LineageEdge{return{parentLotId:e.parentLotId as string,childLotId:e.childLotId as string,transformationType:e.transformationType as string,createdAt:e.createdAt as string,actorUserId:e.actorUserId as string};}function code(e:unknown,v:number){return typeof e==="object"&&e!==null&&"statusCode" in e&&e.statusCode===v;}
export function createComplianceRepository():ComplianceRepository{if(!hasTableStorageConfiguration()){if(process.env.NODE_ENV==="production")throw new Error("Azure Table Storage configuration is required in production");return new InMemoryComplianceRepository();}return new AzureTableComplianceRepository(createTableClient(process.env.AZURE_STORAGE_COMPLIANCE_TABLE??"Compliance"),createTableClient(process.env.AZURE_STORAGE_LINEAGE_TABLE??"Lineage"));}