import{authorize}from"@bordchamp/authz";import type{ActorContext,EntityStatus}from"@bordchamp/domain";
import{BadRequestException,ConflictException,ForbiddenException,Inject,Injectable,NotFoundException}from"@nestjs/common";
import{COMPLIANCE_REPOSITORY,type ComplianceRepository}from"../compliance/compliance.repository.js";
import{IntegrationsService}from"../integrations/integrations.service.js";
import{RISK_REPOSITORY,RiskConflictError,type RiskAlert,type RiskLimits,type RiskRepository}from"./risk.repository.js";
@Injectable()export class RiskService{
 constructor(@Inject(RISK_REPOSITORY)private risk:RiskRepository,@Inject(COMPLIANCE_REPOSITORY)private compliance:ComplianceRepository,@Inject(IntegrationsService)private integrations:IntegrationsService){}
 async setLimits(actor:ActorContext,organizationId:string,maxTradeValueMinor:number,maxOpenDeliveryExposureMinor:number,etag:string|undefined){this.assert("risk.limit.manage",actor,"active",organizationId);positive(maxTradeValueMinor,"maxTradeValueMinor");positive(maxOpenDeliveryExposureMinor,"maxOpenDeliveryExposureMinor");return this.map(()=>this.risk.setLimits({organizationId,maxTradeValueMinor,maxOpenDeliveryExposureMinor,currencyCode:"XOF",updatedAt:new Date().toISOString()},etag,actor.userId));}
 async getLimits(actor:ActorContext,organizationId:string){this.assert("risk.limit.view",actor,"active",organizationId);return(await this.risk.getLimits(organizationId))??defaults(organizationId);}
 async reserveTradeExposure(sellerOrganizationId:string,buyerOrganizationId:string,tradeId:string,amountMinor:number){positive(amountMinor,"amountMinor");for(const org of [sellerOrganizationId,buyerOrganizationId]){const limits=(await this.risk.getLimits(org))??defaults(org);const existing=await this.risk.listExposures(org);if(existing.some(e=>e.tradeId===tradeId))continue;const total=existing.reduce((sum,e)=>sum+e.amountMinor,0);if(amountMinor>limits.maxTradeValueMinor){await this.createSystemAlert(org,"TRADE_LIMIT_BREACH","critical",tradeId,`Trade ${tradeId} exceeds the configured XOF single-trade limit`);throw new ConflictException("Trade exceeds participant risk limits");}if(total+amountMinor>limits.maxOpenDeliveryExposureMinor){await this.createSystemAlert(org,"DELIVERY_EXPOSURE_BREACH","critical",tradeId,`Trade ${tradeId} exceeds aggregate open-delivery exposure`);throw new ConflictException("Trade exceeds participant risk limits");}}
 for(const org of [sellerOrganizationId,buyerOrganizationId])await this.risk.reserveExposure(org,{tradeId,amountMinor,createdAt:new Date().toISOString()});}
 async releaseTradeExposure(sellerOrganizationId:string,buyerOrganizationId:string,tradeId:string){for(const org of [sellerOrganizationId,buyerOrganizationId])await this.risk.releaseExposure(org,tradeId);}
 async evaluateCondition(organizationId:string,deliveryId:string,temperatureMilliC:number|undefined,oxygenMilliPercent:number|undefined){const temperatureBreach=temperatureMilliC!==undefined&&(temperatureMilliC<0||temperatureMilliC>25_000);const oxygenBreach=oxygenMilliPercent!==undefined&&(oxygenMilliPercent<80_000||oxygenMilliPercent>110_000);if(temperatureBreach||oxygenBreach)return this.createSystemAlert(organizationId,"CONDITION_BREACH","critical",deliveryId,`Delivery condition breach: temperature=${temperatureMilliC??"n/a"}, oxygen=${oxygenMilliPercent??"n/a"}`);return undefined;}
 async scanComplianceExpiry(actor:ActorContext,organizationId:string,warningDays:number){this.assert("risk.alert.resolve",actor,"active",organizationId);if(!Number.isSafeInteger(warningDays)||warningDays<0||warningDays>365)throw new BadRequestException("warningDays must be between 0 and 365");const docs=await this.compliance.listDocuments(organizationId);const threshold=Date.now()+warningDays*24*60*60*1000;const alerts:RiskAlert[]=[];for(const doc of docs){if(doc.status==="approved"&&new Date(doc.validUntil).getTime()<=threshold)alerts.push(await this.createSystemAlert(organizationId,"COMPLIANCE_EXPIRY",new Date(doc.validUntil).getTime()<=Date.now()?"critical":"warning",doc.id,`Compliance document ${doc.documentReference} expires at ${doc.validUntil}`));}return alerts;}
 async listAlerts(actor:ActorContext,organizationId:string){this.assert("risk.alert.view",actor,"active",organizationId);return this.risk.listAlerts(organizationId);}
 async acknowledge(actor:ActorContext,organizationId:string,id:string,etag:string){const alert=await this.requireAlert(organizationId,id);if(alert.status==="resolved")throw new BadRequestException("Resolved alerts are immutable");this.assert("risk.alert.acknowledge",actor,"suspended",organizationId);return this.map(()=>this.risk.acknowledgeAlert(organizationId,id,etag,actor.userId));}
 async resolve(actor:ActorContext,organizationId:string,id:string,resolution:string,etag:string){const alert=await this.requireAlert(organizationId,id);if(alert.status==="resolved")return alert;this.assert("risk.alert.resolve",actor,"suspended",organizationId);return this.map(()=>this.risk.resolveAlert(organizationId,id,resolution,etag,actor.userId));}
 private async createSystemAlert(org:string,type:RiskAlert["type"],severity:RiskAlert["severity"],subjectId:string,message:string){const now=new Date().toISOString();const id=`${type}-${Buffer.from(subjectId).toString("base64url")}`;const alert=await this.risk.createAlert({id,organizationId:org,type,severity,subjectId,message,status:"open",createdAt:now,updatedAt:now},"system");await this.integrations.publishBestEffort("private.risk.alert",[org],alert.id,{alertId:alert.id,type:alert.type,severity:alert.severity,status:alert.status,subjectId:alert.subjectId});return alert;}
 private async requireAlert(org:string,id:string){const a=await this.risk.getAlert(org,id);if(!a)throw new NotFoundException("Risk alert not found");return a;}private assert(action:"risk.limit.view"|"risk.limit.manage"|"risk.alert.view"|"risk.alert.acknowledge"|"risk.alert.resolve",actor:ActorContext,state:EntityStatus,org:string){const r=authorize({action,actor,entityStatus:state,resourceOrganizationId:org});if(!r.allowed)throw new ForbiddenException(r.reason);}private async map<T>(op:()=>Promise<T>){try{return await op();}catch(e){if(e instanceof RiskConflictError)throw new ConflictException("Risk state changed; refresh and retry");throw e;}}}
function defaults(organizationId:string):RiskLimits{return{organizationId,maxTradeValueMinor:Number.MAX_SAFE_INTEGER,maxOpenDeliveryExposureMinor:Number.MAX_SAFE_INTEGER,currencyCode:"XOF",updatedAt:"1970-01-01T00:00:00.000Z",etag:""};}function positive(v:number,n:string){if(!Number.isSafeInteger(v)||v<=0)throw new BadRequestException(`${n} must be a positive safe integer`);}