import { TableClient, TableTransaction, type TableEntity } from "@azure/data-tables";
import { randomUUID } from "node:crypto";
import { createTableClient, hasTableStorageConfiguration } from "../storage/table-client.js";

export const RISK_REPOSITORY = Symbol("RISK_REPOSITORY");
export interface RiskLimits { readonly organizationId:string;readonly maxTradeValueMinor:number;
  readonly maxOpenDeliveryExposureMinor:number;readonly currencyCode:"XOF";readonly updatedAt:string;readonly etag:string; }
export interface RiskExposure { readonly tradeId:string;readonly amountMinor:number;readonly createdAt:string; }
export interface RiskAlert { readonly id:string;readonly organizationId:string;
  readonly type:"TRADE_LIMIT_BREACH"|"DELIVERY_EXPOSURE_BREACH"|"CONDITION_BREACH"|"COMPLIANCE_EXPIRY";
  readonly severity:"warning"|"critical";readonly subjectId:string;readonly message:string;
  readonly status:"open"|"acknowledged"|"resolved";readonly createdAt:string;readonly updatedAt:string;
  readonly acknowledgedAt?:string;readonly acknowledgedByUserId?:string;readonly resolvedAt?:string;
  readonly resolvedByUserId?:string;readonly resolution?:string;readonly etag:string; }
export class RiskConflictError extends Error {}
export interface RiskRepository {
  getLimits(organizationId:string):Promise<RiskLimits|undefined>;
  setLimits(value:Omit<RiskLimits,"etag">,etag:string|undefined,actorUserId:string):Promise<RiskLimits>;
  listExposures(organizationId:string):Promise<readonly RiskExposure[]>;
  reserveExposure(organizationId:string,exposure:RiskExposure):Promise<void>;
  releaseExposure(organizationId:string,tradeId:string):Promise<void>;
  createAlert(value:Omit<RiskAlert,"etag">,actorUserId:string):Promise<RiskAlert>;
  getAlert(organizationId:string,id:string):Promise<RiskAlert|undefined>;
  listAlerts(organizationId:string):Promise<readonly RiskAlert[]>;
  acknowledgeAlert(organizationId:string,id:string,etag:string,actorUserId:string):Promise<RiskAlert>;
  resolveAlert(organizationId:string,id:string,resolution:string,etag:string,actorUserId:string):Promise<RiskAlert>;
}
interface LimitEntity extends TableEntity{organizationId:string;maxTradeValueMinor:number;maxOpenDeliveryExposureMinor:number;currencyCode:"XOF";updatedAt:string;}
interface AlertEntity extends TableEntity{id:string;organizationId:string;type:RiskAlert["type"];severity:RiskAlert["severity"];subjectId:string;message:string;status:RiskAlert["status"];createdAt:string;updatedAt:string;acknowledgedAt?:string;acknowledgedByUserId?:string;resolvedAt?:string;resolvedByUserId?:string;resolution?:string;}
function limitEntity(v:Omit<RiskLimits,"etag">):LimitEntity{return{partitionKey:`ORG:${v.organizationId}`,rowKey:"LIMITS",organizationId:v.organizationId,maxTradeValueMinor:v.maxTradeValueMinor,maxOpenDeliveryExposureMinor:v.maxOpenDeliveryExposureMinor,currencyCode:v.currencyCode,updatedAt:v.updatedAt};}
function toLimit(e:LimitEntity&{etag?:string}):RiskLimits{return{organizationId:e.organizationId,maxTradeValueMinor:e.maxTradeValueMinor,maxOpenDeliveryExposureMinor:e.maxOpenDeliveryExposureMinor,currencyCode:e.currencyCode,updatedAt:e.updatedAt,etag:e.etag??""};}
function alertEntity(v:Omit<RiskAlert,"etag">):AlertEntity{return{partitionKey:`ORG:${v.organizationId}`,rowKey:`ALERT:${v.id}`,id:v.id,organizationId:v.organizationId,type:v.type,severity:v.severity,subjectId:v.subjectId,message:v.message,status:v.status,createdAt:v.createdAt,updatedAt:v.updatedAt,...(v.acknowledgedAt===undefined?{}:{acknowledgedAt:v.acknowledgedAt}),...(v.acknowledgedByUserId===undefined?{}:{acknowledgedByUserId:v.acknowledgedByUserId}),...(v.resolvedAt===undefined?{}:{resolvedAt:v.resolvedAt}),...(v.resolvedByUserId===undefined?{}:{resolvedByUserId:v.resolvedByUserId}),...(v.resolution===undefined?{}:{resolution:v.resolution})};}
function toAlert(e:AlertEntity&{etag?:string}):RiskAlert{return{id:e.id,organizationId:e.organizationId,type:e.type,severity:e.severity,subjectId:e.subjectId,message:e.message,status:e.status,createdAt:e.createdAt,updatedAt:e.updatedAt,...(e.acknowledgedAt===undefined?{}:{acknowledgedAt:e.acknowledgedAt}),...(e.acknowledgedByUserId===undefined?{}:{acknowledgedByUserId:e.acknowledgedByUserId}),...(e.resolvedAt===undefined?{}:{resolvedAt:e.resolvedAt}),...(e.resolvedByUserId===undefined?{}:{resolvedByUserId:e.resolvedByUserId}),...(e.resolution===undefined?{}:{resolution:e.resolution}),etag:e.etag??""};}
function event(org:string,type:string,actor:string,at:string,details:string):TableEntity{return{partitionKey:`ORG:${org}`,rowKey:`EVENT:${at}:${randomUUID()}`,eventType:type,actorUserId:actor,occurredAt:at,details};}
abstract class BaseRiskRepository implements RiskRepository {abstract getLimits(o:string):Promise<RiskLimits|undefined>;abstract setLimits(v:Omit<RiskLimits,"etag">,etag:string|undefined,a:string):Promise<RiskLimits>;abstract listExposures(o:string):Promise<readonly RiskExposure[]>;abstract reserveExposure(o:string,e:RiskExposure):Promise<void>;abstract releaseExposure(o:string,t:string):Promise<void>;abstract createAlert(v:Omit<RiskAlert,"etag">,a:string):Promise<RiskAlert>;abstract getAlert(o:string,id:string):Promise<RiskAlert|undefined>;abstract listAlerts(o:string):Promise<readonly RiskAlert[]>;abstract change(o:string,id:string,etag:string,a:string,type:string,apply:(x:RiskAlert,n:string)=>RiskAlert):Promise<RiskAlert>;
 acknowledgeAlert(o:string,id:string,etag:string,a:string){return this.change(o,id,etag,a,"risk.alertAcknowledged",(x,n)=>({...x,status:"acknowledged",acknowledgedAt:n,acknowledgedByUserId:a}));}
 resolveAlert(o:string,id:string,resolution:string,etag:string,a:string){return this.change(o,id,etag,a,"risk.alertResolved",(x,n)=>({...x,status:"resolved",resolvedAt:n,resolvedByUserId:a,resolution}));}}
export class InMemoryRiskRepository extends BaseRiskRepository{private limits=new Map<string,RiskLimits>();private exposures=new Map<string,Map<string,RiskExposure>>();private alerts=new Map<string,RiskAlert>();private version=0;
 async getLimits(o:string){return this.limits.get(o);}async setLimits(v:Omit<RiskLimits,"etag">,etag:string|undefined){const c=this.limits.get(v.organizationId);if(c&&c.etag!==etag)throw new RiskConflictError(v.organizationId);const x={...v,etag:this.next()};this.limits.set(v.organizationId,x);return x;}async listExposures(o:string){return[...(this.exposures.get(o)?.values()??[])];}async reserveExposure(o:string,e:RiskExposure){const m=this.exposures.get(o)??new Map<string,RiskExposure>();m.set(e.tradeId,e);this.exposures.set(o,m);}async releaseExposure(o:string,t:string){this.exposures.get(o)?.delete(t);}async createAlert(v:Omit<RiskAlert,"etag">){const k=`${v.organizationId}:${v.id}`;const c=this.alerts.get(k);if(c)return c;const x={...v,etag:this.next()};this.alerts.set(k,x);return x;}async getAlert(o:string,id:string){return this.alerts.get(`${o}:${id}`);}async listAlerts(o:string){return[...this.alerts.values()].filter(a=>a.organizationId===o);}async change(o:string,id:string,etag:string,_a:string,_t:string,apply:(x:RiskAlert,n:string)=>RiskAlert){const k=`${o}:${id}`;const c=this.alerts.get(k);if(!c||c.etag!==etag)throw new RiskConflictError(id);const n=new Date().toISOString();const x={...apply(c,n),updatedAt:n,etag:this.next()};this.alerts.set(k,x);return x;}private next(){this.version+=1;return`W/\"${this.version}\"`;}}
export class AzureTableRiskRepository extends BaseRiskRepository{constructor(private table:TableClient){super();}
 async getLimits(o:string){try{return toLimit(await this.table.getEntity<LimitEntity>(`ORG:${o}`,"LIMITS"));}catch(e){if(code(e,404))return undefined;throw e;}}
 async setLimits(v:Omit<RiskLimits,"etag">,etag:string|undefined,a:string){const tx=new TableTransaction();if(etag===undefined)tx.createEntity(limitEntity(v));else tx.updateEntity(limitEntity(v),"Replace",{etag});tx.createEntity(event(v.organizationId,"risk.limitsUpdated",a,v.updatedAt,JSON.stringify(v)));await this.submit(tx);return this.requireLimits(v.organizationId);}
 async listExposures(o:string){const out:RiskExposure[]=[];for await(const e of this.table.listEntities({queryOptions:{filter:`PartitionKey eq 'ORG:${o}' and RowKey ge 'EXPOSURE:' and RowKey lt 'EXPOSURF:'`}}))out.push({tradeId:(e as Record<string,unknown>).tradeId as string,amountMinor:(e as Record<string,unknown>).amountMinor as number,createdAt:(e as Record<string,unknown>).createdAt as string});return out;}
 async reserveExposure(o:string,e:RiskExposure){await this.table.upsertEntity({partitionKey:`ORG:${o}`,rowKey:`EXPOSURE:${e.tradeId}`,...e},"Replace");}
 async releaseExposure(o:string,t:string){try{await this.table.deleteEntity(`ORG:${o}`,`EXPOSURE:${t}`);}catch(e){if(!code(e,404))throw e;}}
 async createAlert(v:Omit<RiskAlert,"etag">,a:string){const c=await this.getAlert(v.organizationId,v.id);if(c)return c;const tx=new TableTransaction();tx.createEntity(alertEntity(v));tx.createEntity(event(v.organizationId,"risk.alertCreated",a,v.createdAt,v.id));await this.submit(tx);return this.requireAlert(v.organizationId,v.id);}
 async getAlert(o:string,id:string){try{return toAlert(await this.table.getEntity<AlertEntity>(`ORG:${o}`,`ALERT:${id}`));}catch(e){if(code(e,404))return undefined;throw e;}}
 async listAlerts(o:string){const out:RiskAlert[]=[];for await(const e of this.table.listEntities<AlertEntity>({queryOptions:{filter:`PartitionKey eq 'ORG:${o}' and RowKey ge 'ALERT:' and RowKey lt 'ALES:'`}}))out.push(toAlert(e));return out;}
 async change(o:string,id:string,etag:string,a:string,type:string,apply:(x:RiskAlert,n:string)=>RiskAlert){const c=await this.requireAlert(o,id);const n=new Date().toISOString();const x={...apply(c,n),updatedAt:n};const tx=new TableTransaction();tx.updateEntity(alertEntity(x),"Replace",{etag});tx.createEntity(event(o,type,a,n,id));await this.submit(tx);return this.requireAlert(o,id);}
 private async requireLimits(o:string){const x=await this.getLimits(o);if(!x)throw new Error("Risk limits not found");return x;}private async requireAlert(o:string,id:string){const x=await this.getAlert(o,id);if(!x)throw new Error("Risk alert not found");return x;}private async submit(tx:TableTransaction){try{await this.table.submitTransaction(tx.actions);}catch(e){if(code(e,409)||code(e,412))throw new RiskConflictError("Risk conflict");throw e;}}}
function code(e:unknown,v:number){return typeof e==="object"&&e!==null&&"statusCode" in e&&e.statusCode===v;}
export function createRiskRepository():RiskRepository{if(!hasTableStorageConfiguration()){if(process.env.NODE_ENV==="production")throw new Error("Azure Table Storage configuration is required in production");return new InMemoryRiskRepository();}return new AzureTableRiskRepository(createTableClient(process.env.AZURE_STORAGE_RISK_TABLE??"Risk"));}