import { authorize } from "@bordchamp/authz";import type{ActorContext,EntityStatus}from"@bordchamp/domain";
import{BadRequestException,ConflictException,ForbiddenException,Inject,Injectable,NotFoundException}from"@nestjs/common";
import{DELIVERY_REPOSITORY,type DeliveryRepository}from"../delivery/delivery.repository.js";
import{SETTLEMENT_REPOSITORY,type SettlementRepository}from"../settlement/settlement.repository.js";
import{SettlementService}from"../settlement/settlement.service.js";
import{DISPUTE_REPOSITORY,DisputeConflictError,type Dispute,type DisputeEvidence,type DisputeRepository,type DisputeResponse}from"./dispute.repository.js";
@Injectable()export class DisputesService{
  constructor(@Inject(DISPUTE_REPOSITORY)private disputes:DisputeRepository,@Inject(DELIVERY_REPOSITORY)private deliveries:DeliveryRepository,@Inject(SETTLEMENT_REPOSITORY)private settlements:SettlementRepository,@Inject(SettlementService)private settlementService:SettlementService){}
  async file(actor:ActorContext,deliveryId:string,reasonCode:string,description:string,refs:readonly string[]){const delivery=await this.deliveries.get(deliveryId);if(!delivery)throw new NotFoundException("Delivery not found");if(!["partiallyAccepted","rejected"].includes(delivery.status))throw new BadRequestException("Only partial or rejected deliveries may be disputed");const org=partyOrganization(actor,delivery.sellerOrganizationId,delivery.buyerOrganizationId);this.assert("dispute.file",actor,"active",org);if(Date.now()-new Date(delivery.updatedAt).getTime()>7*24*60*60*1000)throw new BadRequestException("Dispute filing deadline has passed");const id=`DIS-${delivery.id}`;const existing=await this.disputes.get(id);if(existing)return existing;const now=new Date().toISOString();return this.disputes.create({id,deliveryId:delivery.id,settlementId:delivery.settlementId,tradeId:delivery.tradeId,sellerOrganizationId:delivery.sellerOrganizationId,buyerOrganizationId:delivery.buyerOrganizationId,filedByOrganizationId:org,reasonCode,description,status:"open",createdAt:now,updatedAt:now},refs,actor.userId);}
  async get(actor:ActorContext,id:string){const d=await this.require(id);const org=partyOrganizationForRead(actor,d);this.assert("dispute.view",actor,status(d.status),org);return{dispute:d,evidence:await this.disputes.listEvidence(id),responses:await this.disputes.listResponses(id)};}
  async addEvidence(actor:ActorContext,id:string,reference:string,description:string){const d=await this.requireOpen(id);const org=partyOrganization(actor,d.sellerOrganizationId,d.buyerOrganizationId);this.assert("dispute.participate",actor,"active",org);const now=new Date().toISOString();const e:DisputeEvidence={id:randomId("EVID"),organizationId:org,evidenceReference:reference,description,submittedAt:now};await this.map(()=>this.disputes.addEvidence(id,e,actor.userId));return e;}
  async respond(actor:ActorContext,id:string,message:string,refs:readonly string[]){const d=await this.requireOpen(id);const org=partyOrganization(actor,d.sellerOrganizationId,d.buyerOrganizationId);this.assert("dispute.participate",actor,"active",org);const r:DisputeResponse={id:randomId("RESP"),organizationId:org,message,evidenceReferences:refs,submittedAt:new Date().toISOString()};await this.map(()=>this.disputes.addResponse(id,r,actor.userId));return r;}
  async mediate(actor:ActorContext,id:string,etag:string){const d=await this.require(id);if(d.status!=="open")throw new BadRequestException("Only open disputes can enter mediation");this.assert("dispute.resolve",actor,"active",d.sellerOrganizationId);return this.map(()=>this.disputes.startMediation(id,etag,actor.userId));}
  async decide(actor:ActorContext,id:string,remedy:"release"|"refund",rationale:string,etag:string){const d=await this.require(id);if(d.status!=="mediation")throw new BadRequestException("Dispute must be in mediation");this.assert("dispute.resolve",actor,"suspended",d.sellerOrganizationId);const settlement=await this.settlements.get(d.settlementId);if(!settlement)throw new NotFoundException("Settlement not found");if(settlement.status==="deliveryHold")await this.settlementService.resolveDeliveryHold(settlement.id,remedy,settlement.etag,d.id);else if(!((remedy==="refund"&&["refundPending","refunded"].includes(settlement.status))||(remedy==="release"&&["releasePending","released"].includes(settlement.status))))throw new BadRequestException("Settlement state cannot accept this remedy");return this.map(()=>this.disputes.resolve(id,remedy,rationale,etag,actor.userId));}
  private async require(id:string){const d=await this.disputes.get(id);if(!d)throw new NotFoundException("Dispute not found");return d;}private async requireOpen(id:string){const d=await this.require(id);if(d.status==="resolved")throw new BadRequestException("Resolved disputes are immutable");return d;}
  private assert(action:"dispute.file"|"dispute.view"|"dispute.participate"|"dispute.resolve",actor:ActorContext,state:EntityStatus,org:string){const r=authorize({action,actor,entityStatus:state,resourceOrganizationId:org});if(!r.allowed)throw new ForbiddenException(r.reason);}private async map<T>(op:()=>Promise<T>){try{return await op();}catch(e){if(e instanceof DisputeConflictError)throw new ConflictException("Dispute changed; refresh and retry");throw e;}}}
function partyOrganization(actor:ActorContext,seller:string,buyer:string){if(actor.organizationId===seller)return seller;if(actor.organizationId===buyer)return buyer;if(actor.representedOrganizationIds.includes(seller))return seller;if(actor.representedOrganizationIds.includes(buyer))return buyer;throw new ForbiddenException("Actor is not a dispute party");}
function partyOrganizationForRead(actor:ActorContext,d:Dispute){if(actor.personas.includes("ExchangeAdmin")||actor.personas.includes("Regulator"))return d.sellerOrganizationId;return partyOrganization(actor,d.sellerOrganizationId,d.buyerOrganizationId);}
function status(s:Dispute["status"]):EntityStatus{return s==="resolved"?"inactive":s==="mediation"?"suspended":"active";}
function randomId(prefix:string){return`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;}