import{authorize}from"@bordchamp/authz";import type{ActorContext}from"@bordchamp/domain";import{BadRequestException,ForbiddenException,Injectable}from"@nestjs/common";import type{TableEntity}from"@azure/data-tables";import{createTableClient,hasTableStorageConfiguration}from"../storage/table-client.js";
type Entity=TableEntity&Record<string,unknown>;
const TABLES=[
 ["organizations",()=>process.env.AZURE_STORAGE_ORGANIZATIONS_TABLE??"Organizations"],
 ["inventory",()=>process.env.AZURE_STORAGE_INVENTORY_TABLE??"Inventory"],
 ["productionUnits",()=>process.env.AZURE_STORAGE_PRODUCTION_UNITS_TABLE??"ProductionUnits"],
 ["inspections",()=>process.env.AZURE_STORAGE_INSPECTIONS_TABLE??"Inspections"],
 ["warehouseReceipts",()=>process.env.AZURE_STORAGE_WAREHOUSE_RECEIPTS_TABLE??"WarehouseReceipts"],
 ["trading",()=>process.env.AZURE_STORAGE_TRADING_TABLE??"Trading"],
 ["settlements",()=>process.env.AZURE_STORAGE_SETTLEMENTS_TABLE??"Settlements"],
 ["deliveries",()=>process.env.AZURE_STORAGE_DELIVERIES_TABLE??"Deliveries"],
 ["disputes",()=>process.env.AZURE_STORAGE_DISPUTES_TABLE??"Disputes"],
 ["compliance",()=>process.env.AZURE_STORAGE_COMPLIANCE_TABLE??"Compliance"],
 ["risk",()=>process.env.AZURE_STORAGE_RISK_TABLE??"Risk"],
]as const;
@Injectable()export class ReadModelsService{
 async erpWorkspace(actor:ActorContext,organizationId:string){this.authorize("reports.view",actor,organizationId);if(!hasTableStorageConfiguration())return emptyWorkspace(organizationId);const values=Object.fromEntries(await Promise.all(TABLES.map(async([module,name])=>[module,await rows(name())])))as Record<string,Entity[]>;const scoped=(module:string,predicate:(entity:Entity)=>boolean=(entity)=>entity.rowKey==="PROFILE")=>(values[module]??[]).filter(entity=>predicate(entity)&&belongsToOrganization(entity,organizationId)).map(toWorkspaceEntity);const trading=values.trading??[];const ownRfqPartitions=new Set(trading.filter(entity=>entity.rowKey==="PROFILE"&&belongsToOrganization(entity,organizationId)).map(entity=>entity.partitionKey));const quotes=trading.filter(entity=>String(entity.rowKey).startsWith("QUOTE:")&&(belongsToOrganization(entity,organizationId)||ownRfqPartitions.has(entity.partitionKey))).map(toWorkspaceEntity);return{organizationId,generatedAt:new Date().toISOString(),organization:scoped("organizations")[0]??null,productionUnits:scoped("productionUnits"),lots:scoped("inventory"),inspections:scoped("inspections"),warehouseReceipts:scoped("warehouseReceipts"),rfqs:scoped("trading"),quotes,trades:scoped("trading",entity=>String(entity.rowKey).startsWith("TRADE:")),settlements:scoped("settlements"),deliveries:scoped("deliveries"),disputes:scoped("disputes"),documents:scoped("compliance",entity=>String(entity.rowKey).startsWith("DOC:")),recalls:scoped("compliance",entity=>entity.rowKey==="PROFILE"),riskAlerts:scoped("risk",entity=>String(entity.rowKey).startsWith("ALERT:"))};}
 async organizationSummary(actor:ActorContext,organizationId:string){this.authorize("reports.view",actor,organizationId);if(!hasTableStorageConfiguration())return emptySummary(organizationId);const[inventory,trading,settlements,deliveries,risk]=await Promise.all([rows(process.env.AZURE_STORAGE_INVENTORY_TABLE??"Inventory"),rows(process.env.AZURE_STORAGE_TRADING_TABLE??"Trading"),rows(process.env.AZURE_STORAGE_SETTLEMENTS_TABLE??"Settlements"),rows(process.env.AZURE_STORAGE_DELIVERIES_TABLE??"Deliveries"),rows(process.env.AZURE_STORAGE_RISK_TABLE??"Risk")]);
 const lots=inventory.filter(e=>e.rowKey==="PROFILE"&&e.ownerOrganizationId===organizationId);const trades=trading.filter(e=>String(e.rowKey).startsWith("TRADE:")&&(e.sellerOrganizationId===organizationId||e.buyerOrganizationId===organizationId));const ownSettlements=settlements.filter(e=>e.rowKey==="PROFILE"&&(e.sellerOrganizationId===organizationId||e.buyerOrganizationId===organizationId));const ownDeliveries=deliveries.filter(e=>e.rowKey==="PROFILE"&&(e.sellerOrganizationId===organizationId||e.buyerOrganizationId===organizationId||e.logisticsOrganizationId===organizationId));const alerts=risk.filter(e=>String(e.rowKey).startsWith("ALERT:")&&e.partitionKey===`ORG:${organizationId}`);
 return{organizationId,generatedAt:new Date().toISOString(),inventoryByStatus:count(lots,"status"),tradeCount:trades.length,grossSoldMinor:sum(trades.filter(e=>e.sellerOrganizationId===organizationId),"grossAmountMinor"),grossBoughtMinor:sum(trades.filter(e=>e.buyerOrganizationId===organizationId),"grossAmountMinor"),feeAmountMinor:sum(trades,"feeAmountMinor"),currencyCode:"XOF",settlementsByStatus:count(ownSettlements,"status"),deliveriesByStatus:count(ownDeliveries,"status"),riskAlertsByStatus:count(alerts,"status")};}
 async publicMarketSummary(){if(!hasTableStorageConfiguration())return{public:true,generatedAt:new Date().toISOString(),currencyCode:"XOF",markets:[]};const trading=await rows(process.env.AZURE_STORAGE_TRADING_TABLE??"Trading");const trades=trading.filter(e=>String(e.rowKey).startsWith("TRADE:"));const groups=new Map<string,{commodityCode:string;tradeCount:number;volume:number;scale:number;unitCode:string;grossAmountMinor:number}>();for(const t of trades){const q=JSON.parse(t.quantityJson as string)as{value:number;scale:number;unitCode:string};const key=`${t.commodityCode}:${q.scale}:${q.unitCode}`;const g=groups.get(key)??{commodityCode:t.commodityCode as string,tradeCount:0,volume:0,scale:q.scale,unitCode:q.unitCode,grossAmountMinor:0};g.tradeCount+=1;g.volume+=q.value;g.grossAmountMinor+=t.grossAmountMinor as number;groups.set(key,g);}return{public:true,generatedAt:new Date().toISOString(),currencyCode:"XOF",markets:[...groups.values()].sort((a,b)=>a.commodityCode.localeCompare(b.commodityCode))};}
 async audit(actor:ActorContext,organizationId:string|undefined,limit:number){if(!Number.isSafeInteger(limit)||limit<1||limit>200)throw new BadRequestException("limit must be 1-200");const global=actor.personas.includes("ExchangeAdmin")||actor.personas.includes("Regulator");if(global){const r=authorize({action:"auditLog.view",actor,entityStatus:"active"});if(!r.allowed)throw new ForbiddenException(r.reason);}else{if(organizationId===undefined)throw new BadRequestException("organizationId is required");this.authorize("auditLog.viewOwn",actor,organizationId);}if(!hasTableStorageConfiguration())return[];const output:Array<Record<string,unknown>>=[];for(const[module,name]of TABLES){const values=await rows(name());const profiles=new Map<string,Entity>();for(const e of values)if(e.rowKey==="PROFILE")profiles.set(e.partitionKey,e);for(const e of values){const row=String(e.rowKey);if(!row.startsWith("EVENT:")&&!row.startsWith("AUDIT:"))continue;const orgs=organizationsFor(module,e.partitionKey,profiles.get(e.partitionKey));if(!global&&!orgs.includes(organizationId!))continue;output.push({module,aggregateId:e.partitionKey,eventType:e.eventType??e.action??"unknown",occurredAt:e.occurredAt??e.timestamp,actorUserId:e.actorUserId??"system",details:e.details??"",organizationIds:orgs});if(output.length>5000)throw new BadRequestException("Audit query exceeds the supported range");}}return output.sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))).slice(0,limit);}
 private authorize(action:"reports.view"|"auditLog.viewOwn",actor:ActorContext,org:string){const r=authorize({action,actor,entityStatus:"active",resourceOrganizationId:org});if(!r.allowed)throw new ForbiddenException(r.reason);}}
async function rows(table:string){const out:Entity[]=[];for await(const e of createTableClient(table).listEntities())out.push(e as Entity);return out;}function count(values:Entity[],field:string){const out:Record<string,number>={};for(const v of values){const k=String(v[field]??"unknown");out[k]=(out[k]??0)+1;}return out;}function sum(values:Entity[],field:string){return values.reduce((s,v)=>s+(typeof v[field]==="number"?v[field]as number:0),0);}function emptySummary(organizationId:string){return{organizationId,generatedAt:new Date().toISOString(),inventoryByStatus:{},tradeCount:0,grossSoldMinor:0,grossBoughtMinor:0,feeAmountMinor:0,currencyCode:"XOF",settlementsByStatus:{},deliveriesByStatus:{},riskAlertsByStatus:{}};}
function organizationsFor(module:string,partition:string,p:Entity|undefined){if(module==="organizations")return[partition];if(module==="risk"&&partition.startsWith("ORG:"))return[partition.slice(4)];if(module==="compliance"&&partition.startsWith("ORG:"))return[partition.slice(4)];if(!p)return[];return["ownerOrganizationId","sellerOrganizationId","buyerOrganizationId","warehouseOrganizationId","logisticsOrganizationId"].map(k=>p[k]).filter((v):v is string=>typeof v==="string");}
function belongsToOrganization(entity:Entity,organizationId:string){if(entity.partitionKey===organizationId||entity.partitionKey===`ORG:${organizationId}`)return true;for(const key of["organizationId","ownerOrganizationId","sellerOrganizationId","buyerOrganizationId","warehouseOrganizationId","logisticsOrganizationId","filedByOrganizationId","pledgeeOrganizationId"]){if(entity[key]===organizationId)return true;}if(typeof entity.invitedBuyersJson==="string"){try{if((JSON.parse(entity.invitedBuyersJson)as unknown[]).includes(organizationId))return true;}catch{}}return false;}
function toWorkspaceEntity(entity:Entity){const output:Record<string,unknown>={id:workspaceId(entity),etag:entity.etag??""};for(const[key,value]of Object.entries(entity)){if(["partitionKey","rowKey","etag","timestamp","odataMetadata","quantityValue","quantityScale","unitCode","quantityJson","invitedBuyersJson"].includes(key))continue;output[key]=value;}if(typeof entity.quantityValue==="number"&&typeof entity.quantityScale==="number"&&typeof entity.unitCode==="string")output.quantity={value:entity.quantityValue,scale:entity.quantityScale,unitCode:entity.unitCode};if(typeof entity.quantityJson==="string")try{output.quantity=JSON.parse(entity.quantityJson)as unknown;}catch{}if(typeof entity.invitedBuyersJson==="string")try{output.invitedBuyerOrganizationIds=JSON.parse(entity.invitedBuyersJson)as unknown;}catch{}return output;}
function workspaceId(entity:Entity){for(const key of["id","quoteId","eventId"]){if(typeof entity[key]==="string")return entity[key];}if(entity.rowKey==="PROFILE")return entity.partitionKey;const row=String(entity.rowKey);return row.includes(":")?row.slice(row.indexOf(":")+1):row;}
function emptyWorkspace(organizationId:string){return{organizationId,generatedAt:new Date().toISOString(),organization:null,productionUnits:[],lots:[],inspections:[],warehouseReceipts:[],rfqs:[],quotes:[],trades:[],settlements:[],deliveries:[],disputes:[],documents:[],recalls:[],riskAlerts:[]};}